apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w0xnzd56j-nodejs
  janus-idp.io/tekton: w0xnzd56j-nodejs
  backstage.io/kubernetes-id: w0xnzd56j-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w0xnzd56j-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
